name: Test e2e task

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main, master]

jobs:
  e2e-task:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install
        shell: bash
        run: npm ci
      - name: run test
        shell: bash
        run: npm run test